### ISSUE TITLE
Enhance standalone install documentation with systemd files and bash scripts ( linux systems (posix))

### ISSUE THREAD

**Issue by jooola** [airsonic/documentation#17]
IMO the standalone way of installation is the best for fast deployment. Tomcat is too heavy.

But the current documentation about the standalone installation doesn't have enough info to get it running properly like a daemon.

Some files are needed like systemd service files and start/stop scripts.

I currenlty have those but @muff1nman wanted to do this !

**Comment by muff1nman** [comment]
#20 but I think jooola mentioned we could do better on the format.

**Comment by jooola** [comment]
Just for the Systemd service : 
Why not use `EnvironmentFile=/var/airsonic/airsonic.conf` ?
See [here](http://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files)

**Comment by muff1nman** [comment]
I was trying to stay with the typical systemd patterns of referencing an env file in the /etc/sysconfig dir (for fedora at least)

**Comment by jooola** [comment]
#20 closed this
