### ISSUE TITLE
install docs

### ISSUE THREAD

**Issue by ganastor** [airsonic/documentation#23]
Wasn't sure if you wanted this reported in here or airsonic.github.io - but your link from the Migrate page needs to be fixed. https://airsonic.github.io/docs/install/ gives a 404 (found on the Migrate page under "Install Airsonic as described in the install guide.") because there is no install.md in the /pages/ directory on the airsonic.github.io repo.

**Comment by hschroedl** [comment]
I'll get on it. Thanks for reporting.

**Comment by jooola** [comment]
I 'll do it @hschroedl don't waste time with a PR
