### ISSUE TITLE
Clarify requirements for Content-Security-Policy behind reverse proxy

### ISSUE THREAD

**Issue by angelo-v** [airsonic/documentation#25]
When running airsonic behind a reverse proxy with restrictive Content-Security-Policy settings the example config mentioned in the documentation may not be enough.

I had to add the following line to my nginx configuration for airsonic, to get it running without errors:
```
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.gstatic.com; img-src 'self' *.akamaized.net; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; frame-src 'self'; object-src 'none'";
```
The documentation should be more specific on what has to be allowed and what may be restricted.

**Comment by jooola** [comment]
Does this only affects HTTP 2  ? Or also HTTP1.1 ?

**Comment by angelo-v** [comment]
I had this problem using HTTP 1.1
