### ISSUE TITLE
Installation Docs should provide guidance on verification of war files

### ISSUE THREAD

**Issue by muff1nman** [airsonic/documentation#57]
The `airsonic.war` file is signed by my [GPG key](http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x0A3F5E91F8364EDF) in a signature file in the github release files (i.e. https://github.com/airsonic/airsonic/releases/download/v10.2.1/airsonic.war.asc). We should update the downloads to include links to the signature files and we should update the docs to provide instructions for verifying the downloaded file with GPG.

**Comment by jooola** [comment]
Ok, download page could be changed too, we have a single WAR, but ~5 download buttons ^^

Will do.

**Comment by jooola** [comment]
Done
