### ISSUE TITLE
share link  disappeared

### ISSUE THREAD

**Issue by jimmurple** [airsonic/documentation#73]
I am running Airsonic 10.4 on ubuntu server 18.04 LTS. At the time of setting it up, everything was fine, I even shared several albums through airsonic share link, but suddenly, without apparent reason, the share link disappeared. I first thought it could be resolved after updating airsonic to the latest version (because I originally installed Airsonic 10.2), but it did not. I try to gather some information here and there on internet, but it seems I'm pretty lonesome. I have openjdk-8-jre installed as required, so I'm a bit lost. Have you ever seen this before ? Or am I missing something, somewhere ? Thank you

**Comment by jooola** [comment]
Would you mind opening the same ticket on the airsonic/airsonic repo ? This repo is meant for documentation. Or simply reach us in the community channel to get some help.
