### ISSUE TITLE
Add page for External Applications documentation

### ISSUE THREAD

**Issue by issuemover631** [airsonic/documentation#9]
<a href="https://github.com/jooola"><img src="https://avatars2.githubusercontent.com/u/19195485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jooola](https://github.com/jooola)**
_Saturday May 27, 2017 at 04:22 GMT_
_Originally opened as https://github.com/Libresonic/documentation/issues/9_

----

**Comment by hschroedl** [comment]
Tell you what, this rebranding business is very confusing to outsiders. 

Anyways: I would love to polish the airsonic documentation a bit. But before I invest time in something you don't actually need (this issue isn't very... expressive): What were you expecting here? I assume something like the [subsonic app site](http://www.subsonic.org/pages/apps.jsp)?

**Comment by jooola** [comment]
I agree that is currently is really confusing, but after we set up a
proper read me with the infos why we forked, everything should go back
in order.

About the documentation yeah you're right this is a page about the
external app that use subsonic API.
Dsub Or Audinaut.

I won't copy paste the subsonic app page, but we could build some more
documentations about it !

**Comment by hschroedl** [comment]
Okay, thanks for the Info, I'll get to it over the weekend.

**Comment by jooola** [comment]
The Apps page is now done, some updates are still welcomed in the future but we now have a nice base page ! thanks to @hschroedl
